services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicación Go
  app:
    build: .
    container_name: taskmanager_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=taskmanager
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - JWT_SECRET=your-super-secret-jwt-key-here
      - PORT=9090
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
